project:
  type: website
  output-dir: _site

website:
  title: "Shivansh Singh"
  navbar: false
  favicon: favicon.svg

format:
  html:
    theme: none
    css: style.css
    toc: false
    format-links: false
  typst:
    papersize: us-letter
    margin:
      top: 0.4in
      bottom: 0.4in
      x: 0.65in
    font-size: 9pt
    output-file: "Resume-ShivanshSingh.pdf"
  docx:
    reference-doc: reference.docx
    output-file: "Resume-ShivanshSingh.docx"
